# Generated by Django 4.2.13 on 2026-04-15 19:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(blank=True, default='Vinelife Church Wilmslow', max_length=255)),
                ('hero_cta_1_label', models.CharField(blank=True, default='Our Mission', max_length=100)),
                ('hero_cta_1_link', models.CharField(blank=True, default='#about', max_length=100)),
                ('hero_cta_2_label', models.CharField(blank=True, default='Get In Touch', max_length=100)),
                ('hero_cta_2_link', models.CharField(blank=True, default='#contact', max_length=100)),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/VinelifeChurchWilmslow')),
                ('mission_title', models.CharField(blank=True, default='Our Mission', max_length=255)),
                ('mission_content', wagtail.fields.RichTextField(blank=True)),
                ('mission_readmore_label', models.CharField(blank=True, default='Read More', max_length=100)),
                ('mission_history_title', models.CharField(blank=True, default='History', max_length=255)),
                ('mission_history', wagtail.fields.RichTextField(blank=True)),
                ('founders_title', models.CharField(blank=True, default='Founders', max_length=255)),
                ('founders_caption', models.CharField(blank=True, default='Robert & Cheryl Larkman - Founders of Vinelife Church', max_length=255)),
                ('founders_content', wagtail.fields.RichTextField(blank=True)),
                ('thought_title', models.CharField(blank=True, default='Thought for the Day', max_length=255)),
                ('worship_title', models.CharField(blank=True, default='Sunday Worship Meetings', max_length=255)),
                ('worship_subtitle', models.CharField(blank=True, default="Stay connected with what's happening at Vinelife Wilmslow", max_length=255)),
                ('special_events_title', models.CharField(blank=True, default='Special Events', max_length=255)),
                ('special_events_subtitle', models.CharField(blank=True, max_length=255)),
                ('groups_title', models.CharField(blank=True, default='Groups at Vinelife Church', max_length=255)),
                ('groups_subtitle', models.CharField(blank=True, default='We have groups for men & women.', max_length=255)),
                ('mens_group_title', models.CharField(blank=True, default="Men's Group", max_length=100)),
                ('mens_group_description', wagtail.fields.RichTextField(blank=True)),
                ('mens_group_meetings', models.CharField(blank=True, default='First and third Mondays of each month evening', max_length=255)),
                ('mens_group_contact', models.CharField(blank=True, default='07957 813360', max_length=20)),
                ('womens_group_title', models.CharField(blank=True, default="Women's Group", max_length=100)),
                ('womens_group_description', wagtail.fields.RichTextField(blank=True)),
                ('womens_group_meetings', models.CharField(blank=True, default='First and third Mondays of each month (morning and evening)', max_length=255)),
                ('womens_group_contact', models.CharField(blank=True, default='07942 876042', max_length=20)),
                ('youtube_channel_title', models.CharField(blank=True, default='YouTube Channel', max_length=255)),
                ('youtube_embed_url', models.URLField(blank=True, help_text='YouTube embed URL (e.g. https://www.youtube.com/embed/VIDEO_ID)')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel link')),
                ('media_library_title', models.CharField(blank=True, default='Media Library', max_length=255)),
                ('media_library_subtitle', models.CharField(blank=True, default='Watch past Vinelife Wilmslow talks and sermons.', max_length=255)),
                ('media_library_main_videos', wagtail.fields.RichTextField(blank=True, help_text='HTML for main videos (iframe embed)')),
                ('media_library_old_streams', wagtail.fields.RichTextField(blank=True, help_text='HTML for old live streams (iframe embed)')),
                ('media_library_playlists', wagtail.fields.RichTextField(blank=True, help_text='HTML for playlists (iframe embed)')),
                ('resources_title', models.CharField(blank=True, default='Resources', max_length=255)),
                ('resources_subtitle', models.CharField(blank=True, default='Explore helpful resources in our community', max_length=255)),
                ('resource_1_title', models.CharField(blank=True, default='Alpha', max_length=100)),
                ('resource_1_url', models.URLField(blank=True, help_text='Alpha website link')),
                ('resource_2_title', models.CharField(blank=True, default='CAP', max_length=100)),
                ('resource_2_url', models.URLField(blank=True, help_text='CAP website link')),
                ('resource_3_title', models.CharField(blank=True, default='Hope Central', max_length=100)),
                ('resource_3_url', models.URLField(blank=True, help_text='Hope Central website link')),
                ('find_us_title', models.CharField(blank=True, default='Find Us', max_length=255)),
                ('map_embed', wagtail.fields.RichTextField(blank=True, help_text='Google Maps embed iframe HTML')),
                ('parking_info', wagtail.fields.RichTextField(blank=True, help_text='Parking information')),
                ('contact_title', models.CharField(blank=True, default='Contact us', max_length=255)),
                ('contact_intro', models.CharField(blank=True, default='Get in touch with us!', max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='info@vinelifewilmslow.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='07957 813360', max_length=30)),
                ('contact_address', models.CharField(blank=True, default='', max_length=255)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram link')),
                ('founders_image', models.ForeignKey(blank=True, help_text='Founders photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('hero_image_1', models.ForeignKey(blank=True, help_text='First hero background image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('hero_image_2', models.ForeignKey(blank=True, help_text='Second hero background image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('resource_1_img', models.ForeignKey(blank=True, help_text='Alpha logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('resource_2_img', models.ForeignKey(blank=True, help_text='CAP logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('resource_3_img', models.ForeignKey(blank=True, help_text='Hope Central logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
