# Generated by Django 4.2.13 on 2026-04-22 18:53

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HopeCentralPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('mission_title', models.CharField(blank=True, default='About Hope Central', max_length=255)),
                ('mission_content', wagtail.fields.RichTextField(blank=True, help_text='Hope Central mission and overview')),
                ('services_title', models.CharField(blank=True, default='Services We Offer', max_length=255)),
                ('services_content', wagtail.fields.RichTextField(blank=True, help_text='Food bank, pantry, job club, debt centre, money management, Alpha, Hope Centres')),
                ('impact_title', models.CharField(blank=True, default='Our Impact', max_length=255)),
                ('referrals_2024', models.CharField(blank=True, default='3,400+', help_text='Number of referrals in 2024', max_length=100)),
                ('meals_2024', models.CharField(blank=True, default='65,500', help_text='Number of meals provided in 2024', max_length=100)),
                ('impact_content', wagtail.fields.RichTextField(blank=True, help_text='Impact stats and stories')),
                ('involved_title', models.CharField(blank=True, default='Get Involved', max_length=255)),
                ('volunteer_content', wagtail.fields.RichTextField(blank=True, help_text='Volunteering opportunities')),
                ('donate_url', models.URLField(blank=True, default='https://cafdonate.cafonline.org/17913')),
                ('contact_title', models.CharField(blank=True, default='Contact Us', max_length=255)),
                ('contact_info', wagtail.fields.RichTextField(blank=True, help_text='Contact information and hours')),
                ('phone', models.CharField(blank=True, default='01625 724 133', max_length=20)),
                ('email', models.EmailField(blank=True, default='info@hopecentral.org.uk', max_length=254)),
                ('website_url', models.URLField(blank=True, default='https://www.hopecentral.org.uk')),
                ('mission_image', models.ForeignKey(blank=True, help_text='Hope Central logo or image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CAPPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('about_title', models.CharField(blank=True, default='What is CAP?', max_length=255)),
                ('about_content', wagtail.fields.RichTextField(blank=True, help_text='Introduction to CAP')),
                ('services_title', models.CharField(blank=True, default='Our Services', max_length=255)),
                ('services_content', wagtail.fields.RichTextField(blank=True, help_text='Details about CAP services: debt help, money coaching, job clubs, life skills')),
                ('impact_title', models.CharField(blank=True, default='Our Impact', max_length=255)),
                ('impact_content', wagtail.fields.RichTextField(blank=True, help_text='Impact stories and statistics')),
                ('people_helped', models.CharField(blank=True, default='35,000+', help_text='Number of people helped', max_length=100)),
                ('youtube_title', models.CharField(blank=True, default='CAP Videos', max_length=255)),
                ('youtube_embed_1', models.URLField(blank=True, help_text='YouTube embed URL 1')),
                ('youtube_embed_2', models.URLField(blank=True, help_text='YouTube embed URL 2')),
                ('youtube_channel_url', models.URLField(blank=True, help_text='CAP YouTube channel URL')),
                ('local_title', models.CharField(blank=True, default='CAP at Vinelife Wilmslow', max_length=255)),
                ('local_services', wagtail.fields.RichTextField(blank=True, help_text='Services available at Vinelife/Hope Central')),
                ('help_title', models.CharField(blank=True, default='Get Free Help', max_length=255)),
                ('help_intro', wagtail.fields.RichTextField(blank=True, help_text='How to access CAP support')),
                ('cap_website_url', models.URLField(blank=True, default='https://www.capuk.org/get-help/debt-help')),
                ('local_contact', models.CharField(blank=True, help_text='Local contact info for referrals', max_length=255)),
                ('about_image', models.ForeignKey(blank=True, help_text='CAP logo or image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AlphaCoursePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('overview_title', models.CharField(blank=True, default='What is Alpha?', max_length=255)),
                ('overview_content', wagtail.fields.RichTextField(blank=True, help_text='Description of Alpha course')),
                ('covered_title', models.CharField(blank=True, default="What's Covered", max_length=255)),
                ('covered_content', wagtail.fields.RichTextField(blank=True, help_text='Topics and sessions covered in the course')),
                ('why_join_title', models.CharField(blank=True, default='Why Join Alpha?', max_length=255)),
                ('why_join_content', wagtail.fields.RichTextField(blank=True, help_text='Benefits and reasons to join')),
                ('youtube_title', models.CharField(blank=True, default='Alpha Videos', max_length=255)),
                ('youtube_embed_1', models.URLField(blank=True, help_text='YouTube embed URL 1')),
                ('youtube_embed_2', models.URLField(blank=True, help_text='YouTube embed URL 2')),
                ('youtube_playlist_url', models.URLField(blank=True, help_text='Alpha YouTube playlist URL')),
                ('local_title', models.CharField(blank=True, default='Alpha at Vinelife Wilmslow', max_length=255)),
                ('local_info', wagtail.fields.RichTextField(blank=True, help_text='Local session times and contact info')),
                ('signup_title', models.CharField(blank=True, default='Sign Up Today', max_length=255)),
                ('signup_intro', models.CharField(blank=True, default='Ready to explore faith?', max_length=255)),
                ('alpha_website_url', models.URLField(blank=True, default='https://alpha.org.uk/try-alpha')),
                ('overview_image', models.ForeignKey(blank=True, help_text='Alpha course overview image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
